<?php


use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for user login form.
 */
function redirection_form_user_login_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
 
  $form['#submit'][] = 'redirection_user_login_submit';
  
}

/**
 * Custom submit handler for user login form.
 */
function redirection_user_login_submit(array $form, FormStateInterface $form_state) {
  
  $form_state->setRedirect('<front>');
}
